show_animation: True
multiple_process: False
result_folder_name: /deneme_ppo
########################
#UI CHO Screen
cho_screen: False

#Simulation time
sim_duration: 4

#random: 1, custom: 2
scenario: 1
scenario_seed: 100

#Start time for simulation
start_time: 8

#all: 1, adolescents: 2, adults: 3,  children: 4,  ID: 5
patients: 3

#Dexcom: 1, GuardianRT: 2, Navigator:3
sensor: 1
sensor_seed: 100

#Cozmo: 1, Insulet: 2
insulin_pump: 1

#Basal-Bolus Controller:1, PID-Controller:2, RL-Controller:3
controller: 2